### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by tamas-molnar** [comment]
### -1

Why delete useful information from the README? It's easier to read here that to look into the code and find the information

**Comment by ghost** [comment]
Tommy. What has been removed either duplicates information available via the "-help" flag, or is obvious, or is standard expected behaviour that we don't want to copy into every single README.

What do others think? I prefer minimal, concise, specific, correct, up-to-date  README.  If it's not minimal, it tends not to always be correct or up-to-date.

**Comment by george-angel** [comment]
+1

less tldr, more rtfm

**Comment by tamas-molnar** [comment]
I agree that the READMEs shouldn't duplicate standard information, but in this case it's not standard (also, not all conventions are documented in a central location). The `__health` is standard, but I would also expect a `__gtg` for the aggregate healthcheck, for example.

If the README didn't contain the `__ping` endpoint I wouldn't have known it exists without looking in the code. 

The default values are also useful to have in the README, again to avoid always looking in the code. 

An alternative to making the README too large is to document stuff in the code and then let services like godoc expose them, for example: https://godoc.org/github.com/Financial-Times/message-queue-gonsumer/consumer

This is empty: https://godoc.org/github.com/Financial-Times/subjects-rw-neo4j, but the subjects package is ok: https://godoc.org/github.com/Financial-Times/subjects-rw-neo4j/subjects.

**Comment by ghost** [comment]
+1 for prefering godoc to README.md where it makes sense, and pointing to godoc from the README.md

**Comment by tosan88** [comment]
I think this is not relevant anymore, I'll close it

**Pull request closed without merging**
